import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './components/Providers';
import NavBar from './components/NavBar';
import Footer from './components/Footer';
const inter = Inter({ subsets: ['latin'] });
import ScrollToTop from './components/ScrollToTop';
import Head from 'next/head';

export const metadata: Metadata = {
  title: 'Social Media App',
  description: 'Generated by create next app',
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <title>Social Media App</title>
      </Head>
      <body className={inter.className}>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <Providers>
          <NavBar />
          {children}
          <ScrollToTop />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
